/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.*;
import polo.tpo1.agenda.logica.Logica;

/**
 *
 * @author profl
 */
public class Agenda extends javax.swing.JFrame {

    private Font f_nada = new Font("Calibri", 2, 11);
    private Font f_text = new Font("Verdana", 3, 14);

    /**
     * Creates new form Agenda
     */
    private Logica agenda = new Logica();

    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl0Fondo = new javax.swing.JPanel();
        pnl1Titulo = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        pnl1Datos = new javax.swing.JPanel();
        lblDni2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblDni3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDni7 = new javax.swing.JLabel();
        pnl2Datos = new javax.swing.JPanel();
        lblDni4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblDni5 = new javax.swing.JLabel();
        lblDni6 = new javax.swing.JLabel();
        txtFecNacio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPuntero = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPO1 Desarrollo Full Stack con Java");
        setBackground(new java.awt.Color(196, 190, 168));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl0Fondo.setBackground(new java.awt.Color(135, 133, 119));
        pnl0Fondo.setMinimumSize(new java.awt.Dimension(800, 400));
        pnl0Fondo.setOpaque(false);
        pnl0Fondo.setPreferredSize(new java.awt.Dimension(800, 400));

        pnl1Titulo.setBackground(new java.awt.Color(135, 133, 119));
        pnl1Titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl1Titulo.setMinimumSize(new java.awt.Dimension(800, 400));
        pnl1Titulo.setOpaque(false);
        pnl1Titulo.setPreferredSize(new java.awt.Dimension(800, 400));

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(84, 89, 57));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agenda Electrónica");
        lblTitulo.setFocusable(false);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitulo.setMaximumSize(new java.awt.Dimension(504, 60));
        lblTitulo.setMinimumSize(new java.awt.Dimension(504, 60));
        lblTitulo.setPreferredSize(new java.awt.Dimension(504, 60));
        lblTitulo.setVerifyInputWhenFocusTarget(false);

        pnl1Datos.setBackground(new java.awt.Color(101, 107, 62));
        pnl1Datos.setForeground(new java.awt.Color(255, 255, 255));
        pnl1Datos.setPreferredSize(new java.awt.Dimension(400, 200));
        pnl1Datos.setRequestFocusEnabled(false);
        pnl1Datos.setVerifyInputWhenFocusTarget(false);

        lblDni2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDni2.setForeground(new java.awt.Color(255, 255, 204));
        lblDni2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDni2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/dni32.png"))); // NOI18N
        lblDni2.setText("DOCUMENTO  :");
        lblDni2.setAlignmentX(1.0F);
        lblDni2.setAlignmentY(1.0F);
        lblDni2.setMaximumSize(new java.awt.Dimension(60, 18));
        lblDni2.setMinimumSize(new java.awt.Dimension(60, 19));
        lblDni2.setPreferredSize(new java.awt.Dimension(145, 32));

        txtDni.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtDni.setForeground(new java.awt.Color(105, 160, 80));
        txtDni.setText("Ingrese D.N.I. sin puntos ni espacios.");
        txtDni.setAlignmentX(0.0F);
        txtDni.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniFocusLost(evt);
            }
        });
        txtDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDniMouseExited(evt);
            }
        });
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniKeyPressed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(105, 160, 80));
        txtNombre.setText("Ingrese Nombre completo.");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombreMouseExited(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        lblDni3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDni3.setForeground(new java.awt.Color(255, 255, 204));
        lblDni3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/nombre32.png"))); // NOI18N
        lblDni3.setText("APELLIDO         :");
        lblDni3.setAlignmentX(1.0F);
        lblDni3.setAlignmentY(1.0F);
        lblDni3.setMaximumSize(new java.awt.Dimension(60, 18));
        lblDni3.setMinimumSize(new java.awt.Dimension(60, 19));
        lblDni3.setPreferredSize(new java.awt.Dimension(150, 32));

        txtApellido.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(105, 160, 80));
        txtApellido.setText("Ingrese Allidos completos.");
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtApellidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtApellidoMouseExited(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });

        lblDni7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDni7.setForeground(new java.awt.Color(255, 255, 204));
        lblDni7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDni7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/nombre32.png"))); // NOI18N
        lblDni7.setText("NOMBRE          : ");
        lblDni7.setAlignmentX(1.0F);
        lblDni7.setAlignmentY(1.0F);
        lblDni7.setMaximumSize(new java.awt.Dimension(60, 18));
        lblDni7.setMinimumSize(new java.awt.Dimension(60, 19));
        lblDni7.setPreferredSize(new java.awt.Dimension(150, 32));

        javax.swing.GroupLayout pnl1DatosLayout = new javax.swing.GroupLayout(pnl1Datos);
        pnl1Datos.setLayout(pnl1DatosLayout);
        pnl1DatosLayout.setHorizontalGroup(
            pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1DatosLayout.createSequentialGroup()
                        .addComponent(lblDni2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl1DatosLayout.createSequentialGroup()
                        .addGroup(pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDni7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl1DatosLayout.setVerticalGroup(
            pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl2Datos.setBackground(new java.awt.Color(101, 107, 62));
        pnl2Datos.setPreferredSize(new java.awt.Dimension(400, 200));

        lblDni4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDni4.setForeground(new java.awt.Color(255, 255, 204));
        lblDni4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDni4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/telefono32.png"))); // NOI18N
        lblDni4.setText("TELÉFONO  :");
        lblDni4.setAlignmentX(1.0F);
        lblDni4.setAlignmentY(1.0F);
        lblDni4.setMaximumSize(new java.awt.Dimension(60, 18));
        lblDni4.setMinimumSize(new java.awt.Dimension(60, 18));
        lblDni4.setPreferredSize(new java.awt.Dimension(150, 32));

        txtTelefono.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(105, 160, 80));
        txtTelefono.setText("Ingrese Telefono queda como texto.");
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseExited(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
        });

        txtDireccion.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(105, 160, 80));
        txtDireccion.setText("Ingrese Calle, Nro. y Localidad.");
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDireccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDireccionMouseExited(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });

        lblDni5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDni5.setForeground(new java.awt.Color(255, 255, 204));
        lblDni5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDni5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/direccion32.png"))); // NOI18N
        lblDni5.setText("DIRECCIÓN  : ");
        lblDni5.setAlignmentX(1.0F);
        lblDni5.setAlignmentY(1.0F);
        lblDni5.setMaximumSize(new java.awt.Dimension(60, 18));
        lblDni5.setMinimumSize(new java.awt.Dimension(60, 18));
        lblDni5.setPreferredSize(new java.awt.Dimension(150, 32));

        lblDni6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDni6.setForeground(new java.awt.Color(255, 255, 204));
        lblDni6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDni6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/fechanacio32.png"))); // NOI18N
        lblDni6.setText("FECHA NAC. :");
        lblDni6.setAlignmentX(1.0F);
        lblDni6.setAlignmentY(1.0F);
        lblDni6.setMaximumSize(new java.awt.Dimension(60, 18));
        lblDni6.setMinimumSize(new java.awt.Dimension(60, 18));
        lblDni6.setPreferredSize(new java.awt.Dimension(150, 32));

        txtFecNacio.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        txtFecNacio.setForeground(new java.awt.Color(105, 160, 80));
        txtFecNacio.setText("Ingrese fecha formato: DD/MM/AAAA");
        txtFecNacio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFecNacioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFecNacioFocusLost(evt);
            }
        });
        txtFecNacio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFecNacioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFecNacioMouseExited(evt);
            }
        });
        txtFecNacio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFecNacioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnl2DatosLayout = new javax.swing.GroupLayout(pnl2Datos);
        pnl2Datos.setLayout(pnl2DatosLayout);
        pnl2DatosLayout.setHorizontalGroup(
            pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDni6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecNacio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl2DatosLayout.setVerticalGroup(
            pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2DatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl2DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecNacio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlBotones.setBackground(new java.awt.Color(135, 133, 119));
        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBotones.setOpaque(false);
        pnlBotones.setPreferredSize(new java.awt.Dimension(800, 131));
        pnlBotones.setRequestFocusEnabled(false);
        pnlBotones.setVerifyInputWhenFocusTarget(false);

        btnGuardar.setBackground(new java.awt.Color(101, 107, 62));
        btnGuardar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/grabar32.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(200, 64));
        btnGuardar.setMinimumSize(new java.awt.Dimension(200, 64));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAvanzar.setBackground(new java.awt.Color(101, 107, 62));
        btnAvanzar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnAvanzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/avanzar32.png"))); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.setMaximumSize(new java.awt.Dimension(160, 64));
        btnAvanzar.setMinimumSize(new java.awt.Dimension(160, 64));
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        btnRetroceder.setBackground(new java.awt.Color(101, 107, 62));
        btnRetroceder.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/retroceder32.png"))); // NOI18N
        btnRetroceder.setText("Retroceder");
        btnRetroceder.setMaximumSize(new java.awt.Dimension(160, 64));
        btnRetroceder.setMinimumSize(new java.awt.Dimension(160, 64));
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Indice: ");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 32));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 32));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 32));

        txtPuntero.setEditable(false);
        txtPuntero.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtPuntero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuntero.setText("0");
        txtPuntero.setMaximumSize(new java.awt.Dimension(40, 19));
        txtPuntero.setMinimumSize(new java.awt.Dimension(40, 19));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtPuntero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuntero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl1TituloLayout = new javax.swing.GroupLayout(pnl1Titulo);
        pnl1Titulo.setLayout(pnl1TituloLayout);
        pnl1TituloLayout.setHorizontalGroup(
            pnl1TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1TituloLayout.createSequentialGroup()
                        .addGroup(pnl1TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl1TituloLayout.createSequentialGroup()
                        .addGroup(pnl1TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl1TituloLayout.createSequentialGroup()
                                .addComponent(pnl1Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl2Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))))
        );
        pnl1TituloLayout.setVerticalGroup(
            pnl1TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl2Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl1Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout pnl0FondoLayout = new javax.swing.GroupLayout(pnl0Fondo);
        pnl0Fondo.setLayout(pnl0FondoLayout);
        pnl0FondoLayout.setHorizontalGroup(
            pnl0FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(pnl0FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl0FondoLayout.createSequentialGroup()
                    .addComponent(pnl1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl0FondoLayout.setVerticalGroup(
            pnl0FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(pnl0FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl0FondoLayout.createSequentialGroup()
                    .addComponent(pnl1Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pnl0Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/silicon.fondo.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * >>>> Manejo de los Botones
     */
    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        atrasarPuntero();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        avanzarPuntero();      
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        limpiarPantalla();
    }//GEN-LAST:event_formWindowActivated

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarRegistro();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * >>>> Manejo de las cajas de texto
     */
    private void txtDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniFocusGained
        cajaEntra(txtDni, 1);
    }//GEN-LAST:event_txtDniFocusGained

    private void txtDniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniMouseEntered
        cajaEntra(txtDni, 1);
    }//GEN-LAST:event_txtDniMouseEntered

    private void txtDniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniMouseExited
        cajaSale(txtDni, 1);
    }//GEN-LAST:event_txtDniMouseExited

    private void txtDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniFocusLost
        cajaSale(txtDni, 1);
    }//GEN-LAST:event_txtDniFocusLost

    private void txtDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyPressed
        cajaEntra(txtDni, 1);
    }//GEN-LAST:event_txtDniKeyPressed

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        cajaEntra(txtNombre, 2);
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        cajaSale(txtNombre, 2);
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        cajaEntra(txtNombre, 2);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseEntered
        cajaEntra(txtNombre, 2);
    }//GEN-LAST:event_txtNombreMouseEntered

    private void txtNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseExited
        cajaSale(txtNombre, 2);
    }//GEN-LAST:event_txtNombreMouseExited

    private void txtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusGained
        cajaEntra(txtApellido, 3);
    }//GEN-LAST:event_txtApellidoFocusGained

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        cajaSale(txtApellido, 3);
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        cajaEntra(txtApellido, 3);
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtApellidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseEntered
        cajaEntra(txtApellido, 3);
    }//GEN-LAST:event_txtApellidoMouseEntered

    private void txtApellidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseExited
        cajaSale(txtApellido, 3);
    }//GEN-LAST:event_txtApellidoMouseExited

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusGained
        cajaEntra(txtDireccion, 4);
    }//GEN-LAST:event_txtDireccionFocusGained

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        cajaSale(txtDireccion, 4);
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        cajaEntra(txtDireccion, 4);
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtDireccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseEntered
        cajaEntra(txtDireccion, 4);
    }//GEN-LAST:event_txtDireccionMouseEntered

    private void txtDireccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseExited
        cajaSale(txtDireccion, 4);
    }//GEN-LAST:event_txtDireccionMouseExited

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
        cajaEntra(txtTelefono, 5);
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        cajaSale(txtTelefono, 5);
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        cajaEntra(txtTelefono, 5);
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtTelefonoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseEntered
        cajaEntra(txtTelefono, 5);
    }//GEN-LAST:event_txtTelefonoMouseEntered

    private void txtTelefonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseExited
        cajaSale(txtTelefono, 5);
    }//GEN-LAST:event_txtTelefonoMouseExited

    private void txtFecNacioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecNacioFocusGained
        cajaEntra(txtFecNacio, 6);
    }//GEN-LAST:event_txtFecNacioFocusGained

    private void txtFecNacioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecNacioFocusLost
        cajaSale(txtFecNacio, 6);
    }//GEN-LAST:event_txtFecNacioFocusLost

    private void txtFecNacioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFecNacioKeyPressed
        cajaEntra(txtFecNacio, 6);
    }//GEN-LAST:event_txtFecNacioKeyPressed

    private void txtFecNacioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFecNacioMouseEntered
        cajaEntra(txtFecNacio, 6);
    }//GEN-LAST:event_txtFecNacioMouseEntered

    private void txtFecNacioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFecNacioMouseExited
        cajaSale(txtFecNacio, 6);
    }//GEN-LAST:event_txtFecNacioMouseExited

    /**
     * **********************************
     * METODOS COLABORAN CON LA PANTALLA **********************************
     */
    private void limpiarPantalla() {

        agenda.iniciarV();
        txtPuntero.setText(agenda.getPuntero());
        iniciarCajas();

    }

    private void formatearCajas(boolean tieneDato) {
        if (tieneDato) {
//            cajaEntra(txtDni, 0);
//            cajaEntra(txtNombre, 0);
//            cajaEntra(txtApellido, 0);
//            cajaEntra(txtDireccion, 0);
//            cajaEntra(txtTelefono,0 );
//            cajaEntra(txtFecNacio,0 );
            cajaEntra(txtDni, 1);
            cajaEntra(txtNombre, 2);
            cajaEntra(txtApellido, 3);
            cajaEntra(txtDireccion, 4);
            cajaEntra(txtTelefono, 5);
            cajaEntra(txtFecNacio, 6);
        } else {
//            cajaSale(txtDni, 0);
//            cajaSale(txtNombre, 0);
//            cajaSale(txtApellido, 0);
//            cajaSale(txtDireccion, 0);
//            cajaSale(txtTelefono, 0);
//            cajaSale(txtFecNacio, 0);
            cajaSale(txtDni, 1);
            cajaSale(txtNombre, 2);
            cajaSale(txtApellido, 3);
            cajaSale(txtDireccion, 4);
            cajaSale(txtTelefono, 5);
            cajaSale(txtFecNacio, 6);
        }
    }

    private void iniciarCajas() {
        cajaInicial(txtDni, 1);
        cajaInicial(txtNombre, 2);
        cajaInicial(txtApellido, 3);
        cajaInicial(txtDireccion, 4);
        cajaInicial(txtTelefono, 5);
        cajaInicial(txtFecNacio, 6);
    }

    private void avanzarPuntero() {

        agenda.avanzarPuntero(true); // Avanza un lugar si se puede.
        agenda.puntearPersona();     // Prepara las variables
        actualizaPantalla();         // Actualiza la pantalla
 
        formatearCajas(!agenda.getDniP().equals(""));
        // si el DNI está vacio significa que no tiene valores guardados.

    }

    private void atrasarPuntero() {

        agenda.atrazarPuntero(true);  // Retrocede uno lugar si se puede.
        agenda.puntearPersona();      // Prepara las variables
        actualizaPantalla();          // Actualiza la pantalla

        formatearCajas(!agenda.getDniP().equals(""));
        // si el DNI está vacio significa que no tiene valores guardados.
    }

    private void guardarRegistro() {
        /**
         * *
         * Para guardar: 1) prepara las variables 2) guarda en el vector
         */
        actualizaRegistro();
        agenda.guardarPersona();
    }

    private void actualizaPantalla() {

        // Escribe lo que tiene en los vectores
        txtPuntero.setText(agenda.getPuntero()); // Actualiza indice
        txtDni.setText(agenda.getDniP());
        txtNombre.setText(agenda.getNameP());
        txtApellido.setText(agenda.getLastnameP());
        txtDireccion.setText(agenda.getAddressP());
        txtTelefono.setText(agenda.getPhoneP());
        txtFecNacio.setText(agenda.getDatebornP());
    }

    private void actualizaRegistro() {

        // Actualiza lo que tiene en los vectores
        txtPuntero.setText(agenda.getPuntero()); // Actualiza indice
        agenda.setDniP(txtDni.getText());
        agenda.setNameP(txtNombre.getText());
        agenda.setLastnameP(txtApellido.getText());
        agenda.setAddressP(txtDireccion.getText());
        agenda.setPhoneP(txtTelefono.getText());
        agenda.setDatebornP(txtFecNacio.getText());

    }

    /**
     * Complementa las acciones de los eventos de las cajas de texto.
     */
    private void cajaEntra(javax.swing.JTextField caja, int cajaDato) {
        String textoVer = "";
        switch (cajaDato) {

            case 1:
                textoVer = "Ingrese D.N.I. sin puntos ni espacios.";
                break;
            case 2:
                textoVer = "Ingrese Nombre completo.";
                break;
            case 3:
                textoVer = "Ingrese Allidos completos.";
                break;
            case 4:
                textoVer = "Ingrese Calle, Nro. y Localidad.";
                break;
            case 5:
                textoVer = "Ingrese Telefono queda como texto.";
                break;
            case 6:
                textoVer = "Ingrese fecha formato: DD/MM/AAAA";
                break;

        }

        if (caja.getText().equals(textoVer) ) {
            caja.setText("");
            caja.setFont(f_text);
            caja.setForeground(Color.BLUE);
        }
        if (!caja.getText().equals("")){
            caja.setFont(f_text);
            caja.setForeground(Color.BLUE);
        }
        
    }

    private void cajaSale(javax.swing.JTextField caja, int cajaDato) {
        String textoVer = "";
        switch (cajaDato) {

            case 1:
                textoVer = "Ingrese D.N.I. sin puntos ni espacios.";
                break;
            case 2:
                textoVer = "Ingrese Nombre completo.";
                break;
            case 3:
                textoVer = "Ingrese Allidos completos.";
                break;
            case 4:
                textoVer = "Ingrese Calle, Nro. y Localidad.";
                break;
            case 5:
                textoVer = "Ingrese Telefono queda como texto.";
                break;
            case 6:
                textoVer = "Ingrese fecha formato: DD/MM/AAAA";
                break;
        }

        if (caja.getText().equals("")) {
            caja.setText(textoVer);
            caja.setFont(f_nada);
            caja.setForeground(Color.GRAY);

        }


    }

    private void cajaInicial(javax.swing.JTextField caja, int cajaDato) {
        String textoVer = "";
        switch (cajaDato) {
            case 1:
                textoVer = "Ingrese D.N.I. sin puntos ni espacios.";
                break;
            case 2:
                textoVer = "Ingrese Nombre completo.";
                break;
            case 3:
                textoVer = "Ingrese Allidos completos.";
                break;
            case 4:
                textoVer = "Ingrese Calle, Nro. y Localidad.";
                break;
            case 5:
                textoVer = "Ingrese Telefono queda como texto.";
                break;
            case 6:
                textoVer = "Ingrese fecha formato: DD/MM/AAAA";
                break;
        }

        caja.setText(textoVer);
        caja.setFont(f_nada);
        caja.setForeground(Color.GRAY);

    }
 
    


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDni2;
    private javax.swing.JLabel lblDni3;
    private javax.swing.JLabel lblDni4;
    private javax.swing.JLabel lblDni5;
    private javax.swing.JLabel lblDni6;
    private javax.swing.JLabel lblDni7;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnl0Fondo;
    private javax.swing.JPanel pnl1Datos;
    private javax.swing.JPanel pnl1Titulo;
    private javax.swing.JPanel pnl2Datos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFecNacio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuntero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
